-- Search query log for trending analytics
-- Run in Supabase Dashboard → SQL Editor
CREATE TABLE IF NOT EXISTS search_queries (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    query       text        NOT NULL,
    category    text,
    searched_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_sq_searched_at ON search_queries (searched_at DESC);
CREATE INDEX IF NOT EXISTS idx_sq_category    ON search_queries (category);

-- Auto-delete entries older than 90 days (optional, via pg_cron or manual)
-- SELECT cron.schedule('cleanup-search-queries', '0 3 * * *',
--   'DELETE FROM search_queries WHERE searched_at < now() - interval ''90 days''');
