-- "Моята електроника" — user-owned device tracking
-- Run in Supabase Dashboard → SQL Editor

CREATE TABLE IF NOT EXISTS user_devices (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         text        NOT NULL,
    device_name     text        NOT NULL,
    brand           text,
    category        text,
    purchase_date   date,
    purchase_price  numeric(10,2),
    store           text,
    warranty_months int         NOT NULL DEFAULT 24,
    warranty_end    date,
    image_url       text,
    product_url     text,
    notes           text,
    created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ud_user_id     ON user_devices (user_id);
CREATE INDEX IF NOT EXISTS idx_ud_warranty    ON user_devices (warranty_end);

-- Auto-compute warranty_end on insert/update
CREATE OR REPLACE FUNCTION _set_warranty_end()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.purchase_date IS NOT NULL THEN
        NEW.warranty_end := NEW.purchase_date + (NEW.warranty_months || ' months')::interval;
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_warranty_end ON user_devices;
CREATE TRIGGER trg_warranty_end
    BEFORE INSERT OR UPDATE ON user_devices
    FOR EACH ROW EXECUTE FUNCTION _set_warranty_end();
