-- Click tracking — изходящи кликове към магазините (фунията: разговор → клик → покупка)
-- Run in Supabase Dashboard → SQL Editor
CREATE TABLE IF NOT EXISTS click_events (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_url  text        NOT NULL,
    store        text,
    product_name text,
    query        text,          -- какво е търсил потребителят (intent)
    price        numeric,
    email        text,          -- ако е логнат/абониран (иначе NULL)
    session_id   text,          -- анонимна сесия (localStorage)
    clicked_at   timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_click_events_clicked_at ON click_events (clicked_at DESC);
CREATE INDEX IF NOT EXISTS idx_click_events_store      ON click_events (store);
CREATE INDEX IF NOT EXISTS idx_click_events_email      ON click_events (email);

-- Пример: най-кликаните магазини за последните 30 дни
--   SELECT store, count(*) FROM click_events
--   WHERE clicked_at > now() - interval '30 days'
--   GROUP BY store ORDER BY 2 DESC;
