-- Интент-базирани deal alerts: "известявай ме при силна оферта за [това, което търсих]"
-- Run in Supabase Dashboard → SQL Editor
CREATE TABLE IF NOT EXISTS deal_subscriptions (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           text        NOT NULL,
    query           text        NOT NULL,       -- какво търси потребителят (intent)
    category        text,
    min_discount    int         NOT NULL DEFAULT 20,   -- известявай само при отстъпка >= %
    active          boolean     NOT NULL DEFAULT true,
    unsub_token     text        NOT NULL,        -- за 1-клик отписване (GDPR)
    user_id         text,                        -- попълва се във Фаза 2 (Google login)
    last_alerted_at timestamptz,
    created_at      timestamptz NOT NULL DEFAULT now()
);

-- Дедупликация: един имейл + една заявка = един абонамент
CREATE UNIQUE INDEX IF NOT EXISTS idx_deal_sub_email_query
    ON deal_subscriptions (lower(email), lower(query));
CREATE INDEX IF NOT EXISTS idx_deal_sub_active ON deal_subscriptions (active);
CREATE INDEX IF NOT EXISTS idx_deal_sub_email  ON deal_subscriptions (lower(email));
